// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using DevExpress.CodedUIExtension.DXTestControls.v21_2;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod_ThanhToan - Use 'RecordedMethod_ThanhToanParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod_ThanhToan()
        {
            #region Variable Declarations
            DXButton uIItem101PhòngThườngSốButton = this.UIQuảnlýkháchsạnWindow.UIItem101PhòngThườngSốButton;
            DXButton uIThanhtoánButton = this.UIThôngtinphòng101Window.UIThanhtoánButton;
            WinEdit uIGiảmtrừEdit = this.UIThanhtoánWindow.UIGiảmtrừSpinner.UIGiảmtrừEdit;
            WinButton uIThanhtoánButton1 = this.UIThanhtoánWindow.UIThanhtoánWindow1.UIThanhtoánButton;
            WinButton uIYesButton = this.UIThôngbáoWindow.UIYesWindow.UIYesButton;
            WinText uIThanhtoánthànhcôngText = this.UIThanhtoánWindow.UIThanhtoánthànhcôngWindow.UIThanhtoánthànhcôngText;
            #endregion

            // Click '101
            //Phòng Thường
            //Số người: 2' button
            Mouse.Click(uIItem101PhòngThườngSốButton, new Point(1, 1));

            // Click 'Thanh toán' button
            Mouse.Click(uIThanhtoánButton, new Point(1, 1));

            // Click 'Giảm trừ:' text box
            Mouse.Click(uIGiảmtrừEdit, new Point(28, 8));

            // Type '{Back}40000' in 'Giảm trừ:' text box
            Keyboard.SendKeys(uIGiảmtrừEdit, this.RecordedMethod_ThanhToanParams.UIGiảmtrừEditSendKeys, ModifierKeys.None);

            // Click 'Thanh toán' button
            Mouse.Click(uIThanhtoánButton1, new Point(36, 13));

            // Click '&Yes' button
            Mouse.Click(uIYesButton, new Point(42, 15));

            // Click 'Thanh toán thành công.' label
            Mouse.Click(uIThanhtoánthànhcôngText, new Point(94, 17));
        }
        
        /// <summary>
        /// AssertMethod_ThanhToan - Use 'AssertMethod_ThanhToanExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod_ThanhToan()
        {
            #region Variable Declarations
            WinText uIThanhtoánthànhcôngText = this.UIThanhtoánWindow.UIThanhtoánthànhcôngWindow.UIThanhtoánthànhcôngText;
            #endregion

            // Verify that the 'ControlType' property of 'Thanh toán thành công.' label equals 'Thanh toán thành công.'
            Assert.AreEqual(this.AssertMethod_ThanhToanExpectedValues.UIThanhtoánthànhcôngTextControlType, uIThanhtoánthànhcôngText.DisplayText.ToString());
        }
        
        #region Properties
        public virtual RecordedMethod_ThanhToanParams RecordedMethod_ThanhToanParams
        {
            get
            {
                if ((this.mRecordedMethod_ThanhToanParams == null))
                {
                    this.mRecordedMethod_ThanhToanParams = new RecordedMethod_ThanhToanParams();
                }
                return this.mRecordedMethod_ThanhToanParams;
            }
        }
        
        public virtual AssertMethod_ThanhToanExpectedValues AssertMethod_ThanhToanExpectedValues
        {
            get
            {
                if ((this.mAssertMethod_ThanhToanExpectedValues == null))
                {
                    this.mAssertMethod_ThanhToanExpectedValues = new AssertMethod_ThanhToanExpectedValues();
                }
                return this.mAssertMethod_ThanhToanExpectedValues;
            }
        }
        
        public UIQuảnlýkháchsạnWindow UIQuảnlýkháchsạnWindow
        {
            get
            {
                if ((this.mUIQuảnlýkháchsạnWindow == null))
                {
                    this.mUIQuảnlýkháchsạnWindow = new UIQuảnlýkháchsạnWindow();
                }
                return this.mUIQuảnlýkháchsạnWindow;
            }
        }
        
        public UIThôngtinphòng101Window UIThôngtinphòng101Window
        {
            get
            {
                if ((this.mUIThôngtinphòng101Window == null))
                {
                    this.mUIThôngtinphòng101Window = new UIThôngtinphòng101Window();
                }
                return this.mUIThôngtinphòng101Window;
            }
        }
        
        public UIThanhtoánWindow UIThanhtoánWindow
        {
            get
            {
                if ((this.mUIThanhtoánWindow == null))
                {
                    this.mUIThanhtoánWindow = new UIThanhtoánWindow();
                }
                return this.mUIThanhtoánWindow;
            }
        }
        
        public UIThôngbáoWindow UIThôngbáoWindow
        {
            get
            {
                if ((this.mUIThôngbáoWindow == null))
                {
                    this.mUIThôngbáoWindow = new UIThôngbáoWindow();
                }
                return this.mUIThôngbáoWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod_ThanhToanParams mRecordedMethod_ThanhToanParams;
        
        private AssertMethod_ThanhToanExpectedValues mAssertMethod_ThanhToanExpectedValues;
        
        private UIQuảnlýkháchsạnWindow mUIQuảnlýkháchsạnWindow;
        
        private UIThôngtinphòng101Window mUIThôngtinphòng101Window;
        
        private UIThanhtoánWindow mUIThanhtoánWindow;
        
        private UIThôngbáoWindow mUIThôngbáoWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod_ThanhToan'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RecordedMethod_ThanhToanParams
    {
        
        #region Fields
        /// <summary>
        /// Type '{Back}40000' in 'Giảm trừ:' text box
        /// </summary>
        public string UIGiảmtrừEditSendKeys = "{Back}40000";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod_ThanhToan'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class AssertMethod_ThanhToanExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'Thanh toán thành công.' label equals 'Thanh toán thành công.'
        /// </summary>
        public string UIThanhtoánthànhcôngTextControlType = "Thanh toán thành công.";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIQuảnlýkháchsạnWindow : DXWindow
    {
        
        public UIQuảnlýkháchsạnWindow()
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "Quản lý khách sạn";
            this.SearchProperties.Add(new PropertyExpression(DXTestControl.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Quản lý khách sạn");
            #endregion
        }
        
        #region Properties
        public DXButton UIItem101PhòngThườngSốButton
        {
            get
            {
                if ((this.mUIItem101PhòngThườngSốButton == null))
                {
                    this.mUIItem101PhòngThườngSốButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIItem101PhòngThườngSốButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnPhong[0]";
                    this.mUIItem101PhòngThườngSốButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "SimpleButton";
                    this.mUIItem101PhòngThườngSốButton.SearchProperties[DXTestControl.PropertyNames.HierarchyLevel] = "9";
                    this.mUIItem101PhòngThườngSốButton.WindowTitles.Add("Quản lý khách sạn");
                    #endregion
                }
                return this.mUIItem101PhòngThườngSốButton;
            }
        }
        #endregion
        
        #region Fields
        private DXButton mUIItem101PhòngThườngSốButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIThôngtinphòng101Window : WinWindow
    {
        
        public UIThôngtinphòng101Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Thông tin phòng - 101";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Thông tin phòng - 101");
            #endregion
        }
        
        #region Properties
        public DXButton UIThanhtoánButton
        {
            get
            {
                if ((this.mUIThanhtoánButton == null))
                {
                    this.mUIThanhtoánButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIThanhtoánButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnThanhToan";
                    this.mUIThanhtoánButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "SimpleButton";
                    this.mUIThanhtoánButton.SearchProperties[DXTestControl.PropertyNames.HierarchyLevel] = "3";
                    this.mUIThanhtoánButton.WindowTitles.Add("Thông tin phòng - 101");
                    #endregion
                }
                return this.mUIThanhtoánButton;
            }
        }
        #endregion
        
        #region Fields
        private DXButton mUIThanhtoánButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIThanhtoánWindow : WinWindow
    {
        
        public UIThanhtoánWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Thanh toán";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Thanh toán");
            #endregion
        }
        
        #region Properties
        public UIGiảmtrừSpinner UIGiảmtrừSpinner
        {
            get
            {
                if ((this.mUIGiảmtrừSpinner == null))
                {
                    this.mUIGiảmtrừSpinner = new UIGiảmtrừSpinner(this);
                }
                return this.mUIGiảmtrừSpinner;
            }
        }
        
        public UIThanhtoánWindow1 UIThanhtoánWindow1
        {
            get
            {
                if ((this.mUIThanhtoánWindow1 == null))
                {
                    this.mUIThanhtoánWindow1 = new UIThanhtoánWindow1(this);
                }
                return this.mUIThanhtoánWindow1;
            }
        }
        
        public UIThanhtoánthànhcôngWindow UIThanhtoánthànhcôngWindow
        {
            get
            {
                if ((this.mUIThanhtoánthànhcôngWindow == null))
                {
                    this.mUIThanhtoánthànhcôngWindow = new UIThanhtoánthànhcôngWindow(this);
                }
                return this.mUIThanhtoánthànhcôngWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIGiảmtrừSpinner mUIGiảmtrừSpinner;
        
        private UIThanhtoánWindow1 mUIThanhtoánWindow1;
        
        private UIThanhtoánthànhcôngWindow mUIThanhtoánthànhcôngWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIGiảmtrừSpinner : WinSpinner
    {
        
        public UIGiảmtrừSpinner(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinSpinner.PropertyNames.Name] = "Giảm trừ:";
            this.WindowTitles.Add("Thanh toán");
            #endregion
        }
        
        #region Properties
        public WinEdit UIGiảmtrừEdit
        {
            get
            {
                if ((this.mUIGiảmtrừEdit == null))
                {
                    this.mUIGiảmtrừEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIGiảmtrừEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Giảm trừ:";
                    this.mUIGiảmtrừEdit.WindowTitles.Add("Thanh toán");
                    #endregion
                }
                return this.mUIGiảmtrừEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIGiảmtrừEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIThanhtoánWindow1 : WinWindow
    {
        
        public UIThanhtoánWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnThanhToan";
            this.WindowTitles.Add("Thanh toán");
            #endregion
        }
        
        #region Properties
        public WinButton UIThanhtoánButton
        {
            get
            {
                if ((this.mUIThanhtoánButton == null))
                {
                    this.mUIThanhtoánButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIThanhtoánButton.SearchProperties[WinButton.PropertyNames.Name] = "Thanh toán";
                    this.mUIThanhtoánButton.WindowTitles.Add("Thanh toán");
                    #endregion
                }
                return this.mUIThanhtoánButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIThanhtoánButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIThanhtoánthànhcôngWindow : WinWindow
    {
        
        public UIThanhtoánthànhcôngWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "lbResult";
            this.WindowTitles.Add("Thanh toán");
            #endregion
        }
        
        #region Properties
        public WinText UIThanhtoánthànhcôngText
        {
            get
            {
                if ((this.mUIThanhtoánthànhcôngText == null))
                {
                    this.mUIThanhtoánthànhcôngText = new WinText(this);
                    #region Search Criteria
                    this.mUIThanhtoánthànhcôngText.SearchProperties[WinText.PropertyNames.Name] = "Thanh toán thành công.";
                    this.mUIThanhtoánthànhcôngText.WindowTitles.Add("Thanh toán");
                    #endregion
                }
                return this.mUIThanhtoánthànhcôngText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIThanhtoánthànhcôngText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIThôngbáoWindow : WinWindow
    {
        
        public UIThôngbáoWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Thông báo";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Thông báo");
            #endregion
        }
        
        #region Properties
        public UIYesWindow UIYesWindow
        {
            get
            {
                if ((this.mUIYesWindow == null))
                {
                    this.mUIYesWindow = new UIYesWindow(this);
                }
                return this.mUIYesWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIYesWindow mUIYesWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIYesWindow : WinWindow
    {
        
        public UIYesWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "6";
            this.WindowTitles.Add("Thông báo");
            #endregion
        }
        
        #region Properties
        public WinButton UIYesButton
        {
            get
            {
                if ((this.mUIYesButton == null))
                {
                    this.mUIYesButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIYesButton.SearchProperties[WinButton.PropertyNames.Name] = "Yes";
                    this.mUIYesButton.WindowTitles.Add("Thông báo");
                    #endregion
                }
                return this.mUIYesButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIYesButton;
        #endregion
    }
}
