#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbQLKS")]
	public partial class QLKSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_CTDatPhong(tb_CTDatPhong instance);
    partial void Updatetb_CTDatPhong(tb_CTDatPhong instance);
    partial void Deletetb_CTDatPhong(tb_CTDatPhong instance);
    partial void Inserttb_TangLau(tb_TangLau instance);
    partial void Updatetb_TangLau(tb_TangLau instance);
    partial void Deletetb_TangLau(tb_TangLau instance);
    partial void Inserttb_CTDatPhong_SanPham(tb_CTDatPhong_SanPham instance);
    partial void Updatetb_CTDatPhong_SanPham(tb_CTDatPhong_SanPham instance);
    partial void Deletetb_CTDatPhong_SanPham(tb_CTDatPhong_SanPham instance);
    partial void Inserttb_Gia(tb_Gia instance);
    partial void Updatetb_Gia(tb_Gia instance);
    partial void Deletetb_Gia(tb_Gia instance);
    partial void Inserttb_HoaDon(tb_HoaDon instance);
    partial void Updatetb_HoaDon(tb_HoaDon instance);
    partial void Deletetb_HoaDon(tb_HoaDon instance);
    partial void Inserttb_KhachHang(tb_KhachHang instance);
    partial void Updatetb_KhachHang(tb_KhachHang instance);
    partial void Deletetb_KhachHang(tb_KhachHang instance);
    partial void Inserttb_LoaiPhong(tb_LoaiPhong instance);
    partial void Updatetb_LoaiPhong(tb_LoaiPhong instance);
    partial void Deletetb_LoaiPhong(tb_LoaiPhong instance);
    partial void Inserttb_NhanVien(tb_NhanVien instance);
    partial void Updatetb_NhanVien(tb_NhanVien instance);
    partial void Deletetb_NhanVien(tb_NhanVien instance);
    partial void Inserttb_NhomSanPham(tb_NhomSanPham instance);
    partial void Updatetb_NhomSanPham(tb_NhomSanPham instance);
    partial void Deletetb_NhomSanPham(tb_NhomSanPham instance);
    partial void Inserttb_PhieuDatPhong(tb_PhieuDatPhong instance);
    partial void Updatetb_PhieuDatPhong(tb_PhieuDatPhong instance);
    partial void Deletetb_PhieuDatPhong(tb_PhieuDatPhong instance);
    partial void Inserttb_Phong(tb_Phong instance);
    partial void Updatetb_Phong(tb_Phong instance);
    partial void Deletetb_Phong(tb_Phong instance);
    partial void Inserttb_SanPham(tb_SanPham instance);
    partial void Updatetb_SanPham(tb_SanPham instance);
    partial void Deletetb_SanPham(tb_SanPham instance);
    partial void Inserttb_TaiKhoan(tb_TaiKhoan instance);
    partial void Updatetb_TaiKhoan(tb_TaiKhoan instance);
    partial void Deletetb_TaiKhoan(tb_TaiKhoan instance);
    #endregion
		
		public QLKSDataContext() : 
				base(global::DTO.Properties.Settings.Default.dbQLKSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLKSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_CTDatPhong> tb_CTDatPhongs
		{
			get
			{
				return this.GetTable<tb_CTDatPhong>();
			}
		}
		
		public System.Data.Linq.Table<tb_TangLau> tb_TangLaus
		{
			get
			{
				return this.GetTable<tb_TangLau>();
			}
		}
		
		public System.Data.Linq.Table<tb_CTDatPhong_SanPham> tb_CTDatPhong_SanPhams
		{
			get
			{
				return this.GetTable<tb_CTDatPhong_SanPham>();
			}
		}
		
		public System.Data.Linq.Table<tb_Gia> tb_Gias
		{
			get
			{
				return this.GetTable<tb_Gia>();
			}
		}
		
		public System.Data.Linq.Table<tb_HoaDon> tb_HoaDons
		{
			get
			{
				return this.GetTable<tb_HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<tb_KhachHang> tb_KhachHangs
		{
			get
			{
				return this.GetTable<tb_KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<tb_LoaiPhong> tb_LoaiPhongs
		{
			get
			{
				return this.GetTable<tb_LoaiPhong>();
			}
		}
		
		public System.Data.Linq.Table<tb_NhanVien> tb_NhanViens
		{
			get
			{
				return this.GetTable<tb_NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tb_NhomSanPham> tb_NhomSanPhams
		{
			get
			{
				return this.GetTable<tb_NhomSanPham>();
			}
		}
		
		public System.Data.Linq.Table<tb_PhieuDatPhong> tb_PhieuDatPhongs
		{
			get
			{
				return this.GetTable<tb_PhieuDatPhong>();
			}
		}
		
		public System.Data.Linq.Table<tb_Phong> tb_Phongs
		{
			get
			{
				return this.GetTable<tb_Phong>();
			}
		}
		
		public System.Data.Linq.Table<tb_SanPham> tb_SanPhams
		{
			get
			{
				return this.GetTable<tb_SanPham>();
			}
		}
		
		public System.Data.Linq.Table<tb_TaiKhoan> tb_TaiKhoans
		{
			get
			{
				return this.GetTable<tb_TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_CTDatPhong")]
	public partial class tb_CTDatPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCTDatPhong;
		
		private System.Nullable<int> _MaPhieuDat;
		
		private System.Nullable<int> _MaPhong;
		
		private System.Nullable<int> _SoLuongNguoiLon;
		
		private System.Nullable<int> _SoLuongTreEm;
		
		private System.Nullable<System.DateTime> _CheckIn;
		
		private System.Nullable<System.DateTime> _CheckOut;
		
		private EntitySet<tb_CTDatPhong_SanPham> _tb_CTDatPhong_SanPhams;
		
		private EntityRef<tb_PhieuDatPhong> _tb_PhieuDatPhong;
		
		private EntityRef<tb_Phong> _tb_Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTDatPhongChanging(int value);
    partial void OnMaCTDatPhongChanged();
    partial void OnMaPhieuDatChanging(System.Nullable<int> value);
    partial void OnMaPhieuDatChanged();
    partial void OnMaPhongChanging(System.Nullable<int> value);
    partial void OnMaPhongChanged();
    partial void OnSoLuongNguoiLonChanging(System.Nullable<int> value);
    partial void OnSoLuongNguoiLonChanged();
    partial void OnSoLuongTreEmChanging(System.Nullable<int> value);
    partial void OnSoLuongTreEmChanged();
    partial void OnCheckInChanging(System.Nullable<System.DateTime> value);
    partial void OnCheckInChanged();
    partial void OnCheckOutChanging(System.Nullable<System.DateTime> value);
    partial void OnCheckOutChanged();
    #endregion
		
		public tb_CTDatPhong()
		{
			this._tb_CTDatPhong_SanPhams = new EntitySet<tb_CTDatPhong_SanPham>(new Action<tb_CTDatPhong_SanPham>(this.attach_tb_CTDatPhong_SanPhams), new Action<tb_CTDatPhong_SanPham>(this.detach_tb_CTDatPhong_SanPhams));
			this._tb_PhieuDatPhong = default(EntityRef<tb_PhieuDatPhong>);
			this._tb_Phong = default(EntityRef<tb_Phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTDatPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCTDatPhong
		{
			get
			{
				return this._MaCTDatPhong;
			}
			set
			{
				if ((this._MaCTDatPhong != value))
				{
					this.OnMaCTDatPhongChanging(value);
					this.SendPropertyChanging();
					this._MaCTDatPhong = value;
					this.SendPropertyChanged("MaCTDatPhong");
					this.OnMaCTDatPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuDat", DbType="Int")]
		public System.Nullable<int> MaPhieuDat
		{
			get
			{
				return this._MaPhieuDat;
			}
			set
			{
				if ((this._MaPhieuDat != value))
				{
					if (this._tb_PhieuDatPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuDatChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuDat = value;
					this.SendPropertyChanged("MaPhieuDat");
					this.OnMaPhieuDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="Int")]
		public System.Nullable<int> MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					if (this._tb_Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongNguoiLon", DbType="Int")]
		public System.Nullable<int> SoLuongNguoiLon
		{
			get
			{
				return this._SoLuongNguoiLon;
			}
			set
			{
				if ((this._SoLuongNguoiLon != value))
				{
					this.OnSoLuongNguoiLonChanging(value);
					this.SendPropertyChanging();
					this._SoLuongNguoiLon = value;
					this.SendPropertyChanged("SoLuongNguoiLon");
					this.OnSoLuongNguoiLonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongTreEm", DbType="Int")]
		public System.Nullable<int> SoLuongTreEm
		{
			get
			{
				return this._SoLuongTreEm;
			}
			set
			{
				if ((this._SoLuongTreEm != value))
				{
					this.OnSoLuongTreEmChanging(value);
					this.SendPropertyChanging();
					this._SoLuongTreEm = value;
					this.SendPropertyChanged("SoLuongTreEm");
					this.OnSoLuongTreEmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckIn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CheckIn
		{
			get
			{
				return this._CheckIn;
			}
			set
			{
				if ((this._CheckIn != value))
				{
					this.OnCheckInChanging(value);
					this.SendPropertyChanging();
					this._CheckIn = value;
					this.SendPropertyChanged("CheckIn");
					this.OnCheckInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOut", DbType="DateTime")]
		public System.Nullable<System.DateTime> CheckOut
		{
			get
			{
				return this._CheckOut;
			}
			set
			{
				if ((this._CheckOut != value))
				{
					this.OnCheckOutChanging(value);
					this.SendPropertyChanging();
					this._CheckOut = value;
					this.SendPropertyChanged("CheckOut");
					this.OnCheckOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_CTDatPhong_tb_CTDatPhong_SanPham", Storage="_tb_CTDatPhong_SanPhams", ThisKey="MaCTDatPhong", OtherKey="MaCTDatPhong")]
		public EntitySet<tb_CTDatPhong_SanPham> tb_CTDatPhong_SanPhams
		{
			get
			{
				return this._tb_CTDatPhong_SanPhams;
			}
			set
			{
				this._tb_CTDatPhong_SanPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_PhieuDatPhong_tb_CTDatPhong", Storage="_tb_PhieuDatPhong", ThisKey="MaPhieuDat", OtherKey="MaPhieuDat", IsForeignKey=true)]
		public tb_PhieuDatPhong tb_PhieuDatPhong
		{
			get
			{
				return this._tb_PhieuDatPhong.Entity;
			}
			set
			{
				tb_PhieuDatPhong previousValue = this._tb_PhieuDatPhong.Entity;
				if (((previousValue != value) 
							|| (this._tb_PhieuDatPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_PhieuDatPhong.Entity = null;
						previousValue.tb_CTDatPhongs.Remove(this);
					}
					this._tb_PhieuDatPhong.Entity = value;
					if ((value != null))
					{
						value.tb_CTDatPhongs.Add(this);
						this._MaPhieuDat = value.MaPhieuDat;
					}
					else
					{
						this._MaPhieuDat = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_PhieuDatPhong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Phong_tb_CTDatPhong", Storage="_tb_Phong", ThisKey="MaPhong", OtherKey="MaPhong", IsForeignKey=true)]
		public tb_Phong tb_Phong
		{
			get
			{
				return this._tb_Phong.Entity;
			}
			set
			{
				tb_Phong previousValue = this._tb_Phong.Entity;
				if (((previousValue != value) 
							|| (this._tb_Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Phong.Entity = null;
						previousValue.tb_CTDatPhongs.Remove(this);
					}
					this._tb_Phong.Entity = value;
					if ((value != null))
					{
						value.tb_CTDatPhongs.Add(this);
						this._MaPhong = value.MaPhong;
					}
					else
					{
						this._MaPhong = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_CTDatPhong_SanPhams(tb_CTDatPhong_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.tb_CTDatPhong = this;
		}
		
		private void detach_tb_CTDatPhong_SanPhams(tb_CTDatPhong_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.tb_CTDatPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_TangLau")]
	public partial class tb_TangLau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTang;
		
		private string _TenTang;
		
		private int _SoLuongPhong;
		
		private string _GhiChu;
		
		private System.Nullable<int> _SapXep;
		
		private System.Nullable<bool> _DaDay;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<tb_Phong> _tb_Phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTangChanging(int value);
    partial void OnMaTangChanged();
    partial void OnTenTangChanging(string value);
    partial void OnTenTangChanged();
    partial void OnSoLuongPhongChanging(int value);
    partial void OnSoLuongPhongChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnSapXepChanging(System.Nullable<int> value);
    partial void OnSapXepChanged();
    partial void OnDaDayChanging(System.Nullable<bool> value);
    partial void OnDaDayChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public tb_TangLau()
		{
			this._tb_Phongs = new EntitySet<tb_Phong>(new Action<tb_Phong>(this.attach_tb_Phongs), new Action<tb_Phong>(this.detach_tb_Phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTang
		{
			get
			{
				return this._MaTang;
			}
			set
			{
				if ((this._MaTang != value))
				{
					this.OnMaTangChanging(value);
					this.SendPropertyChanging();
					this._MaTang = value;
					this.SendPropertyChanged("MaTang");
					this.OnMaTangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTang", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string TenTang
		{
			get
			{
				return this._TenTang;
			}
			set
			{
				if ((this._TenTang != value))
				{
					this.OnTenTangChanging(value);
					this.SendPropertyChanging();
					this._TenTang = value;
					this.SendPropertyChanged("TenTang");
					this.OnTenTangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongPhong", DbType="Int NOT NULL")]
		public int SoLuongPhong
		{
			get
			{
				return this._SoLuongPhong;
			}
			set
			{
				if ((this._SoLuongPhong != value))
				{
					this.OnSoLuongPhongChanging(value);
					this.SendPropertyChanging();
					this._SoLuongPhong = value;
					this.SendPropertyChanged("SoLuongPhong");
					this.OnSoLuongPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(240)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SapXep", DbType="Int")]
		public System.Nullable<int> SapXep
		{
			get
			{
				return this._SapXep;
			}
			set
			{
				if ((this._SapXep != value))
				{
					this.OnSapXepChanging(value);
					this.SendPropertyChanging();
					this._SapXep = value;
					this.SendPropertyChanged("SapXep");
					this.OnSapXepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaDay", DbType="Bit")]
		public System.Nullable<bool> DaDay
		{
			get
			{
				return this._DaDay;
			}
			set
			{
				if ((this._DaDay != value))
				{
					this.OnDaDayChanging(value);
					this.SendPropertyChanging();
					this._DaDay = value;
					this.SendPropertyChanged("DaDay");
					this.OnDaDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_TangLau_tb_Phong", Storage="_tb_Phongs", ThisKey="MaTang", OtherKey="MaTang")]
		public EntitySet<tb_Phong> tb_Phongs
		{
			get
			{
				return this._tb_Phongs;
			}
			set
			{
				this._tb_Phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Phongs(tb_Phong entity)
		{
			this.SendPropertyChanging();
			entity.tb_TangLau = this;
		}
		
		private void detach_tb_Phongs(tb_Phong entity)
		{
			this.SendPropertyChanging();
			entity.tb_TangLau = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_CTDatPhong_SanPham")]
	public partial class tb_CTDatPhong_SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCTDatPhong;
		
		private int _MaSanPham;
		
		private System.Nullable<int> _SoLuong;
		
		private EntityRef<tb_CTDatPhong> _tb_CTDatPhong;
		
		private EntityRef<tb_SanPham> _tb_SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTDatPhongChanging(int value);
    partial void OnMaCTDatPhongChanged();
    partial void OnMaSanPhamChanging(int value);
    partial void OnMaSanPhamChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public tb_CTDatPhong_SanPham()
		{
			this._tb_CTDatPhong = default(EntityRef<tb_CTDatPhong>);
			this._tb_SanPham = default(EntityRef<tb_SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTDatPhong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaCTDatPhong
		{
			get
			{
				return this._MaCTDatPhong;
			}
			set
			{
				if ((this._MaCTDatPhong != value))
				{
					if (this._tb_CTDatPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCTDatPhongChanging(value);
					this.SendPropertyChanging();
					this._MaCTDatPhong = value;
					this.SendPropertyChanged("MaCTDatPhong");
					this.OnMaCTDatPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					if (this._tb_SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_CTDatPhong_tb_CTDatPhong_SanPham", Storage="_tb_CTDatPhong", ThisKey="MaCTDatPhong", OtherKey="MaCTDatPhong", IsForeignKey=true)]
		public tb_CTDatPhong tb_CTDatPhong
		{
			get
			{
				return this._tb_CTDatPhong.Entity;
			}
			set
			{
				tb_CTDatPhong previousValue = this._tb_CTDatPhong.Entity;
				if (((previousValue != value) 
							|| (this._tb_CTDatPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_CTDatPhong.Entity = null;
						previousValue.tb_CTDatPhong_SanPhams.Remove(this);
					}
					this._tb_CTDatPhong.Entity = value;
					if ((value != null))
					{
						value.tb_CTDatPhong_SanPhams.Add(this);
						this._MaCTDatPhong = value.MaCTDatPhong;
					}
					else
					{
						this._MaCTDatPhong = default(int);
					}
					this.SendPropertyChanged("tb_CTDatPhong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_SanPham_tb_CTDatPhong_SanPham", Storage="_tb_SanPham", ThisKey="MaSanPham", OtherKey="MaSanPham", IsForeignKey=true)]
		public tb_SanPham tb_SanPham
		{
			get
			{
				return this._tb_SanPham.Entity;
			}
			set
			{
				tb_SanPham previousValue = this._tb_SanPham.Entity;
				if (((previousValue != value) 
							|| (this._tb_SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_SanPham.Entity = null;
						previousValue.tb_CTDatPhong_SanPhams.Remove(this);
					}
					this._tb_SanPham.Entity = value;
					if ((value != null))
					{
						value.tb_CTDatPhong_SanPhams.Add(this);
						this._MaSanPham = value.MaSanPham;
					}
					else
					{
						this._MaSanPham = default(int);
					}
					this.SendPropertyChanged("tb_SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Gia")]
	public partial class tb_Gia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenMucGia;
		
		private System.Nullable<int> _MaLoaiPhong;
		
		private decimal _DonGiaNgay;
		
		private decimal _DonGiaDem;
		
		private decimal _DonGiaGio;
		
		private EntityRef<tb_LoaiPhong> _tb_LoaiPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenMucGiaChanging(string value);
    partial void OnTenMucGiaChanged();
    partial void OnMaLoaiPhongChanging(System.Nullable<int> value);
    partial void OnMaLoaiPhongChanged();
    partial void OnDonGiaNgayChanging(decimal value);
    partial void OnDonGiaNgayChanged();
    partial void OnDonGiaDemChanging(decimal value);
    partial void OnDonGiaDemChanged();
    partial void OnDonGiaGioChanging(decimal value);
    partial void OnDonGiaGioChanged();
    #endregion
		
		public tb_Gia()
		{
			this._tb_LoaiPhong = default(EntityRef<tb_LoaiPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMucGia", DbType="NVarChar(60) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenMucGia
		{
			get
			{
				return this._TenMucGia;
			}
			set
			{
				if ((this._TenMucGia != value))
				{
					this.OnTenMucGiaChanging(value);
					this.SendPropertyChanging();
					this._TenMucGia = value;
					this.SendPropertyChanged("TenMucGia");
					this.OnTenMucGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiPhong", DbType="Int")]
		public System.Nullable<int> MaLoaiPhong
		{
			get
			{
				return this._MaLoaiPhong;
			}
			set
			{
				if ((this._MaLoaiPhong != value))
				{
					if (this._tb_LoaiPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiPhong = value;
					this.SendPropertyChanged("MaLoaiPhong");
					this.OnMaLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaNgay", DbType="Money NOT NULL")]
		public decimal DonGiaNgay
		{
			get
			{
				return this._DonGiaNgay;
			}
			set
			{
				if ((this._DonGiaNgay != value))
				{
					this.OnDonGiaNgayChanging(value);
					this.SendPropertyChanging();
					this._DonGiaNgay = value;
					this.SendPropertyChanged("DonGiaNgay");
					this.OnDonGiaNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaDem", DbType="Money NOT NULL")]
		public decimal DonGiaDem
		{
			get
			{
				return this._DonGiaDem;
			}
			set
			{
				if ((this._DonGiaDem != value))
				{
					this.OnDonGiaDemChanging(value);
					this.SendPropertyChanging();
					this._DonGiaDem = value;
					this.SendPropertyChanged("DonGiaDem");
					this.OnDonGiaDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaGio", DbType="Money NOT NULL")]
		public decimal DonGiaGio
		{
			get
			{
				return this._DonGiaGio;
			}
			set
			{
				if ((this._DonGiaGio != value))
				{
					this.OnDonGiaGioChanging(value);
					this.SendPropertyChanging();
					this._DonGiaGio = value;
					this.SendPropertyChanged("DonGiaGio");
					this.OnDonGiaGioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_LoaiPhong_tb_Gia", Storage="_tb_LoaiPhong", ThisKey="MaLoaiPhong", OtherKey="MaLoaiPhong", IsForeignKey=true)]
		public tb_LoaiPhong tb_LoaiPhong
		{
			get
			{
				return this._tb_LoaiPhong.Entity;
			}
			set
			{
				tb_LoaiPhong previousValue = this._tb_LoaiPhong.Entity;
				if (((previousValue != value) 
							|| (this._tb_LoaiPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_LoaiPhong.Entity = null;
						previousValue.tb_Gias.Remove(this);
					}
					this._tb_LoaiPhong.Entity = value;
					if ((value != null))
					{
						value.tb_Gias.Add(this);
						this._MaLoaiPhong = value.MaLoaiPhong;
					}
					else
					{
						this._MaLoaiPhong = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_LoaiPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_HoaDon")]
	public partial class tb_HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHD;
		
		private System.Nullable<int> _MaPhieuDat;
		
		private System.Nullable<decimal> _TongTien;
		
		private System.Nullable<decimal> _GiamTru;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private EntityRef<tb_PhieuDatPhong> _tb_PhieuDatPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(int value);
    partial void OnMaHDChanged();
    partial void OnMaPhieuDatChanging(System.Nullable<int> value);
    partial void OnMaPhieuDatChanged();
    partial void OnTongTienChanging(System.Nullable<decimal> value);
    partial void OnTongTienChanged();
    partial void OnGiamTruChanging(System.Nullable<decimal> value);
    partial void OnGiamTruChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    #endregion
		
		public tb_HoaDon()
		{
			this._tb_PhieuDatPhong = default(EntityRef<tb_PhieuDatPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuDat", DbType="Int")]
		public System.Nullable<int> MaPhieuDat
		{
			get
			{
				return this._MaPhieuDat;
			}
			set
			{
				if ((this._MaPhieuDat != value))
				{
					if (this._tb_PhieuDatPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuDatChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuDat = value;
					this.SendPropertyChanged("MaPhieuDat");
					this.OnMaPhieuDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Money")]
		public System.Nullable<decimal> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamTru", DbType="Money")]
		public System.Nullable<decimal> GiamTru
		{
			get
			{
				return this._GiamTru;
			}
			set
			{
				if ((this._GiamTru != value))
				{
					this.OnGiamTruChanging(value);
					this.SendPropertyChanging();
					this._GiamTru = value;
					this.SendPropertyChanged("GiamTru");
					this.OnGiamTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_PhieuDatPhong_tb_HoaDon", Storage="_tb_PhieuDatPhong", ThisKey="MaPhieuDat", OtherKey="MaPhieuDat", IsForeignKey=true)]
		public tb_PhieuDatPhong tb_PhieuDatPhong
		{
			get
			{
				return this._tb_PhieuDatPhong.Entity;
			}
			set
			{
				tb_PhieuDatPhong previousValue = this._tb_PhieuDatPhong.Entity;
				if (((previousValue != value) 
							|| (this._tb_PhieuDatPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_PhieuDatPhong.Entity = null;
						previousValue.tb_HoaDons.Remove(this);
					}
					this._tb_PhieuDatPhong.Entity = value;
					if ((value != null))
					{
						value.tb_HoaDons.Add(this);
						this._MaPhieuDat = value.MaPhieuDat;
					}
					else
					{
						this._MaPhieuDat = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_PhieuDatPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_KhachHang")]
	public partial class tb_KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CCCD;
		
		private string _HoTen;
		
		private string _DienThoai;
		
		private string _Email;
		
		private string _DiaChi;
		
		private System.Nullable<char> _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<System.DateTime> _NgayCap;
		
		private string _NoiCap;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<tb_PhieuDatPhong> _tb_PhieuDatPhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnGioiTinhChanging(System.Nullable<char> value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnNgayCapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapChanged();
    partial void OnNoiCapChanging(string value);
    partial void OnNoiCapChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public tb_KhachHang()
		{
			this._tb_PhieuDatPhongs = new EntitySet<tb_PhieuDatPhong>(new Action<tb_PhieuDatPhong>(this.attach_tb_PhieuDatPhongs), new Action<tb_PhieuDatPhong>(this.detach_tb_PhieuDatPhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(10)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(60)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(120)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Char(1)")]
		public System.Nullable<char> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayCap
		{
			get
			{
				return this._NgayCap;
			}
			set
			{
				if ((this._NgayCap != value))
				{
					this.OnNgayCapChanging(value);
					this.SendPropertyChanging();
					this._NgayCap = value;
					this.SendPropertyChanged("NgayCap");
					this.OnNgayCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiCap", DbType="NVarChar(120)")]
		public string NoiCap
		{
			get
			{
				return this._NoiCap;
			}
			set
			{
				if ((this._NoiCap != value))
				{
					this.OnNoiCapChanging(value);
					this.SendPropertyChanging();
					this._NoiCap = value;
					this.SendPropertyChanged("NoiCap");
					this.OnNoiCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_KhachHang_tb_PhieuDatPhong", Storage="_tb_PhieuDatPhongs", ThisKey="CCCD", OtherKey="CCCD")]
		public EntitySet<tb_PhieuDatPhong> tb_PhieuDatPhongs
		{
			get
			{
				return this._tb_PhieuDatPhongs;
			}
			set
			{
				this._tb_PhieuDatPhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_PhieuDatPhongs(tb_PhieuDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.tb_KhachHang = this;
		}
		
		private void detach_tb_PhieuDatPhongs(tb_PhieuDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.tb_KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_LoaiPhong")]
	public partial class tb_LoaiPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiPhong;
		
		private string _TenLoaiPhong;
		
		private int _SoLuongNguoiLon;
		
		private int _SoLuongTreEm;
		
		private string _GhiChu;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<tb_Gia> _tb_Gias;
		
		private EntitySet<tb_Phong> _tb_Phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiPhongChanging(int value);
    partial void OnMaLoaiPhongChanged();
    partial void OnTenLoaiPhongChanging(string value);
    partial void OnTenLoaiPhongChanged();
    partial void OnSoLuongNguoiLonChanging(int value);
    partial void OnSoLuongNguoiLonChanged();
    partial void OnSoLuongTreEmChanging(int value);
    partial void OnSoLuongTreEmChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public tb_LoaiPhong()
		{
			this._tb_Gias = new EntitySet<tb_Gia>(new Action<tb_Gia>(this.attach_tb_Gias), new Action<tb_Gia>(this.detach_tb_Gias));
			this._tb_Phongs = new EntitySet<tb_Phong>(new Action<tb_Phong>(this.attach_tb_Phongs), new Action<tb_Phong>(this.detach_tb_Phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiPhong
		{
			get
			{
				return this._MaLoaiPhong;
			}
			set
			{
				if ((this._MaLoaiPhong != value))
				{
					this.OnMaLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiPhong = value;
					this.SendPropertyChanged("MaLoaiPhong");
					this.OnMaLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiPhong", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string TenLoaiPhong
		{
			get
			{
				return this._TenLoaiPhong;
			}
			set
			{
				if ((this._TenLoaiPhong != value))
				{
					this.OnTenLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiPhong = value;
					this.SendPropertyChanged("TenLoaiPhong");
					this.OnTenLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongNguoiLon", DbType="Int NOT NULL")]
		public int SoLuongNguoiLon
		{
			get
			{
				return this._SoLuongNguoiLon;
			}
			set
			{
				if ((this._SoLuongNguoiLon != value))
				{
					this.OnSoLuongNguoiLonChanging(value);
					this.SendPropertyChanging();
					this._SoLuongNguoiLon = value;
					this.SendPropertyChanged("SoLuongNguoiLon");
					this.OnSoLuongNguoiLonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongTreEm", DbType="Int NOT NULL")]
		public int SoLuongTreEm
		{
			get
			{
				return this._SoLuongTreEm;
			}
			set
			{
				if ((this._SoLuongTreEm != value))
				{
					this.OnSoLuongTreEmChanging(value);
					this.SendPropertyChanging();
					this._SoLuongTreEm = value;
					this.SendPropertyChanged("SoLuongTreEm");
					this.OnSoLuongTreEmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(240)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_LoaiPhong_tb_Gia", Storage="_tb_Gias", ThisKey="MaLoaiPhong", OtherKey="MaLoaiPhong")]
		public EntitySet<tb_Gia> tb_Gias
		{
			get
			{
				return this._tb_Gias;
			}
			set
			{
				this._tb_Gias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_LoaiPhong_tb_Phong", Storage="_tb_Phongs", ThisKey="MaLoaiPhong", OtherKey="MaLoaiPhong")]
		public EntitySet<tb_Phong> tb_Phongs
		{
			get
			{
				return this._tb_Phongs;
			}
			set
			{
				this._tb_Phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Gias(tb_Gia entity)
		{
			this.SendPropertyChanging();
			entity.tb_LoaiPhong = this;
		}
		
		private void detach_tb_Gias(tb_Gia entity)
		{
			this.SendPropertyChanging();
			entity.tb_LoaiPhong = null;
		}
		
		private void attach_tb_Phongs(tb_Phong entity)
		{
			this.SendPropertyChanging();
			entity.tb_LoaiPhong = this;
		}
		
		private void detach_tb_Phongs(tb_Phong entity)
		{
			this.SendPropertyChanging();
			entity.tb_LoaiPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_NhanVien")]
	public partial class tb_NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNV;
		
		private string _HoTen;
		
		private string _DienThoai;
		
		private string _Email;
		
		private string _DiaChi;
		
		private System.Nullable<char> _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _CCCD;
		
		private System.Nullable<System.DateTime> _NgayCap;
		
		private string _NoiCap;
		
		private string _TenDangNhap;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<tb_PhieuDatPhong> _tb_PhieuDatPhongs;
		
		private EntityRef<tb_TaiKhoan> _tb_TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnGioiTinhChanging(System.Nullable<char> value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnNgayCapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapChanged();
    partial void OnNoiCapChanging(string value);
    partial void OnNoiCapChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public tb_NhanVien()
		{
			this._tb_PhieuDatPhongs = new EntitySet<tb_PhieuDatPhong>(new Action<tb_PhieuDatPhong>(this.attach_tb_PhieuDatPhongs), new Action<tb_PhieuDatPhong>(this.detach_tb_PhieuDatPhongs));
			this._tb_TaiKhoan = default(EntityRef<tb_TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(10)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(60)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(120)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Char(1)")]
		public System.Nullable<char> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="VarChar(12)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayCap
		{
			get
			{
				return this._NgayCap;
			}
			set
			{
				if ((this._NgayCap != value))
				{
					this.OnNgayCapChanging(value);
					this.SendPropertyChanging();
					this._NgayCap = value;
					this.SendPropertyChanged("NgayCap");
					this.OnNgayCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiCap", DbType="NVarChar(120)")]
		public string NoiCap
		{
			get
			{
				return this._NoiCap;
			}
			set
			{
				if ((this._NoiCap != value))
				{
					this.OnNoiCapChanging(value);
					this.SendPropertyChanging();
					this._NoiCap = value;
					this.SendPropertyChanged("NoiCap");
					this.OnNoiCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(25)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					if (this._tb_TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NhanVien_tb_PhieuDatPhong", Storage="_tb_PhieuDatPhongs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<tb_PhieuDatPhong> tb_PhieuDatPhongs
		{
			get
			{
				return this._tb_PhieuDatPhongs;
			}
			set
			{
				this._tb_PhieuDatPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_TaiKhoan_tb_NhanVien", Storage="_tb_TaiKhoan", ThisKey="TenDangNhap", OtherKey="TenDangNhap", IsForeignKey=true)]
		public tb_TaiKhoan tb_TaiKhoan
		{
			get
			{
				return this._tb_TaiKhoan.Entity;
			}
			set
			{
				tb_TaiKhoan previousValue = this._tb_TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._tb_TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_TaiKhoan.Entity = null;
						previousValue.tb_NhanViens.Remove(this);
					}
					this._tb_TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.tb_NhanViens.Add(this);
						this._TenDangNhap = value.TenDangNhap;
					}
					else
					{
						this._TenDangNhap = default(string);
					}
					this.SendPropertyChanged("tb_TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_PhieuDatPhongs(tb_PhieuDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.tb_NhanVien = this;
		}
		
		private void detach_tb_PhieuDatPhongs(tb_PhieuDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.tb_NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_NhomSanPham")]
	public partial class tb_NhomSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNSP;
		
		private string _TenNSP;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<tb_SanPham> _tb_SanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNSPChanging(int value);
    partial void OnMaNSPChanged();
    partial void OnTenNSPChanging(string value);
    partial void OnTenNSPChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public tb_NhomSanPham()
		{
			this._tb_SanPhams = new EntitySet<tb_SanPham>(new Action<tb_SanPham>(this.attach_tb_SanPhams), new Action<tb_SanPham>(this.detach_tb_SanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNSP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNSP
		{
			get
			{
				return this._MaNSP;
			}
			set
			{
				if ((this._MaNSP != value))
				{
					this.OnMaNSPChanging(value);
					this.SendPropertyChanging();
					this._MaNSP = value;
					this.SendPropertyChanged("MaNSP");
					this.OnMaNSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNSP", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string TenNSP
		{
			get
			{
				return this._TenNSP;
			}
			set
			{
				if ((this._TenNSP != value))
				{
					this.OnTenNSPChanging(value);
					this.SendPropertyChanging();
					this._TenNSP = value;
					this.SendPropertyChanged("TenNSP");
					this.OnTenNSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NhomSanPham_tb_SanPham", Storage="_tb_SanPhams", ThisKey="MaNSP", OtherKey="MaNSP")]
		public EntitySet<tb_SanPham> tb_SanPhams
		{
			get
			{
				return this._tb_SanPhams;
			}
			set
			{
				this._tb_SanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_SanPhams(tb_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.tb_NhomSanPham = this;
		}
		
		private void detach_tb_SanPhams(tb_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.tb_NhomSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_PhieuDatPhong")]
	public partial class tb_PhieuDatPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhieuDat;
		
		private string _CCCD;
		
		private System.Nullable<decimal> _TraTruoc;
		
		private System.Nullable<int> _MaNV;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private System.Nullable<bool> _DaHuy;
		
		private EntitySet<tb_CTDatPhong> _tb_CTDatPhongs;
		
		private EntitySet<tb_HoaDon> _tb_HoaDons;
		
		private EntityRef<tb_KhachHang> _tb_KhachHang;
		
		private EntityRef<tb_NhanVien> _tb_NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuDatChanging(int value);
    partial void OnMaPhieuDatChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnTraTruocChanging(System.Nullable<decimal> value);
    partial void OnTraTruocChanged();
    partial void OnMaNVChanging(System.Nullable<int> value);
    partial void OnMaNVChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnDaHuyChanging(System.Nullable<bool> value);
    partial void OnDaHuyChanged();
    #endregion
		
		public tb_PhieuDatPhong()
		{
			this._tb_CTDatPhongs = new EntitySet<tb_CTDatPhong>(new Action<tb_CTDatPhong>(this.attach_tb_CTDatPhongs), new Action<tb_CTDatPhong>(this.detach_tb_CTDatPhongs));
			this._tb_HoaDons = new EntitySet<tb_HoaDon>(new Action<tb_HoaDon>(this.attach_tb_HoaDons), new Action<tb_HoaDon>(this.detach_tb_HoaDons));
			this._tb_KhachHang = default(EntityRef<tb_KhachHang>);
			this._tb_NhanVien = default(EntityRef<tb_NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuDat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhieuDat
		{
			get
			{
				return this._MaPhieuDat;
			}
			set
			{
				if ((this._MaPhieuDat != value))
				{
					this.OnMaPhieuDatChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuDat = value;
					this.SendPropertyChanged("MaPhieuDat");
					this.OnMaPhieuDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="VarChar(12)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					if (this._tb_KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TraTruoc", DbType="Money")]
		public System.Nullable<decimal> TraTruoc
		{
			get
			{
				return this._TraTruoc;
			}
			set
			{
				if ((this._TraTruoc != value))
				{
					this.OnTraTruocChanging(value);
					this.SendPropertyChanging();
					this._TraTruoc = value;
					this.SendPropertyChanged("TraTruoc");
					this.OnTraTruocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int")]
		public System.Nullable<int> MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._tb_NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaHuy", DbType="Bit")]
		public System.Nullable<bool> DaHuy
		{
			get
			{
				return this._DaHuy;
			}
			set
			{
				if ((this._DaHuy != value))
				{
					this.OnDaHuyChanging(value);
					this.SendPropertyChanging();
					this._DaHuy = value;
					this.SendPropertyChanged("DaHuy");
					this.OnDaHuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_PhieuDatPhong_tb_CTDatPhong", Storage="_tb_CTDatPhongs", ThisKey="MaPhieuDat", OtherKey="MaPhieuDat")]
		public EntitySet<tb_CTDatPhong> tb_CTDatPhongs
		{
			get
			{
				return this._tb_CTDatPhongs;
			}
			set
			{
				this._tb_CTDatPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_PhieuDatPhong_tb_HoaDon", Storage="_tb_HoaDons", ThisKey="MaPhieuDat", OtherKey="MaPhieuDat")]
		public EntitySet<tb_HoaDon> tb_HoaDons
		{
			get
			{
				return this._tb_HoaDons;
			}
			set
			{
				this._tb_HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_KhachHang_tb_PhieuDatPhong", Storage="_tb_KhachHang", ThisKey="CCCD", OtherKey="CCCD", IsForeignKey=true)]
		public tb_KhachHang tb_KhachHang
		{
			get
			{
				return this._tb_KhachHang.Entity;
			}
			set
			{
				tb_KhachHang previousValue = this._tb_KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._tb_KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_KhachHang.Entity = null;
						previousValue.tb_PhieuDatPhongs.Remove(this);
					}
					this._tb_KhachHang.Entity = value;
					if ((value != null))
					{
						value.tb_PhieuDatPhongs.Add(this);
						this._CCCD = value.CCCD;
					}
					else
					{
						this._CCCD = default(string);
					}
					this.SendPropertyChanged("tb_KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NhanVien_tb_PhieuDatPhong", Storage="_tb_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public tb_NhanVien tb_NhanVien
		{
			get
			{
				return this._tb_NhanVien.Entity;
			}
			set
			{
				tb_NhanVien previousValue = this._tb_NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tb_NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_NhanVien.Entity = null;
						previousValue.tb_PhieuDatPhongs.Remove(this);
					}
					this._tb_NhanVien.Entity = value;
					if ((value != null))
					{
						value.tb_PhieuDatPhongs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_CTDatPhongs(tb_CTDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.tb_PhieuDatPhong = this;
		}
		
		private void detach_tb_CTDatPhongs(tb_CTDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.tb_PhieuDatPhong = null;
		}
		
		private void attach_tb_HoaDons(tb_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tb_PhieuDatPhong = this;
		}
		
		private void detach_tb_HoaDons(tb_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tb_PhieuDatPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Phong")]
	public partial class tb_Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhong;
		
		private string _TenPhong;
		
		private System.Nullable<int> _MaLoaiPhong;
		
		private System.Nullable<int> _MaTang;
		
		private string _TrangThai;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<tb_CTDatPhong> _tb_CTDatPhongs;
		
		private EntityRef<tb_LoaiPhong> _tb_LoaiPhong;
		
		private EntityRef<tb_TangLau> _tb_TangLau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChanging(int value);
    partial void OnMaPhongChanged();
    partial void OnTenPhongChanging(string value);
    partial void OnTenPhongChanged();
    partial void OnMaLoaiPhongChanging(System.Nullable<int> value);
    partial void OnMaLoaiPhongChanged();
    partial void OnMaTangChanging(System.Nullable<int> value);
    partial void OnMaTangChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public tb_Phong()
		{
			this._tb_CTDatPhongs = new EntitySet<tb_CTDatPhong>(new Action<tb_CTDatPhong>(this.attach_tb_CTDatPhongs), new Action<tb_CTDatPhong>(this.detach_tb_CTDatPhongs));
			this._tb_LoaiPhong = default(EntityRef<tb_LoaiPhong>);
			this._tb_TangLau = default(EntityRef<tb_TangLau>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhong", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string TenPhong
		{
			get
			{
				return this._TenPhong;
			}
			set
			{
				if ((this._TenPhong != value))
				{
					this.OnTenPhongChanging(value);
					this.SendPropertyChanging();
					this._TenPhong = value;
					this.SendPropertyChanged("TenPhong");
					this.OnTenPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiPhong", DbType="Int")]
		public System.Nullable<int> MaLoaiPhong
		{
			get
			{
				return this._MaLoaiPhong;
			}
			set
			{
				if ((this._MaLoaiPhong != value))
				{
					if (this._tb_LoaiPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiPhong = value;
					this.SendPropertyChanged("MaLoaiPhong");
					this.OnMaLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTang", DbType="Int")]
		public System.Nullable<int> MaTang
		{
			get
			{
				return this._MaTang;
			}
			set
			{
				if ((this._MaTang != value))
				{
					if (this._tb_TangLau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTangChanging(value);
					this.SendPropertyChanging();
					this._MaTang = value;
					this.SendPropertyChanged("MaTang");
					this.OnMaTangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(25)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Phong_tb_CTDatPhong", Storage="_tb_CTDatPhongs", ThisKey="MaPhong", OtherKey="MaPhong")]
		public EntitySet<tb_CTDatPhong> tb_CTDatPhongs
		{
			get
			{
				return this._tb_CTDatPhongs;
			}
			set
			{
				this._tb_CTDatPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_LoaiPhong_tb_Phong", Storage="_tb_LoaiPhong", ThisKey="MaLoaiPhong", OtherKey="MaLoaiPhong", IsForeignKey=true)]
		public tb_LoaiPhong tb_LoaiPhong
		{
			get
			{
				return this._tb_LoaiPhong.Entity;
			}
			set
			{
				tb_LoaiPhong previousValue = this._tb_LoaiPhong.Entity;
				if (((previousValue != value) 
							|| (this._tb_LoaiPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_LoaiPhong.Entity = null;
						previousValue.tb_Phongs.Remove(this);
					}
					this._tb_LoaiPhong.Entity = value;
					if ((value != null))
					{
						value.tb_Phongs.Add(this);
						this._MaLoaiPhong = value.MaLoaiPhong;
					}
					else
					{
						this._MaLoaiPhong = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_LoaiPhong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_TangLau_tb_Phong", Storage="_tb_TangLau", ThisKey="MaTang", OtherKey="MaTang", IsForeignKey=true)]
		public tb_TangLau tb_TangLau
		{
			get
			{
				return this._tb_TangLau.Entity;
			}
			set
			{
				tb_TangLau previousValue = this._tb_TangLau.Entity;
				if (((previousValue != value) 
							|| (this._tb_TangLau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_TangLau.Entity = null;
						previousValue.tb_Phongs.Remove(this);
					}
					this._tb_TangLau.Entity = value;
					if ((value != null))
					{
						value.tb_Phongs.Add(this);
						this._MaTang = value.MaTang;
					}
					else
					{
						this._MaTang = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_TangLau");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_CTDatPhongs(tb_CTDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.tb_Phong = this;
		}
		
		private void detach_tb_CTDatPhongs(tb_CTDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.tb_Phong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_SanPham")]
	public partial class tb_SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSanPham;
		
		private string _TenSanPham;
		
		private decimal _DonGia;
		
		private string _DonViTinh;
		
		private System.Nullable<int> _MaNSP;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<tb_CTDatPhong_SanPham> _tb_CTDatPhong_SanPhams;
		
		private EntityRef<tb_NhomSanPham> _tb_NhomSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSanPhamChanging(int value);
    partial void OnMaSanPhamChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnDonGiaChanging(decimal value);
    partial void OnDonGiaChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    partial void OnMaNSPChanging(System.Nullable<int> value);
    partial void OnMaNSPChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public tb_SanPham()
		{
			this._tb_CTDatPhong_SanPhams = new EntitySet<tb_CTDatPhong_SanPham>(new Action<tb_CTDatPhong_SanPham>(this.attach_tb_CTDatPhong_SanPhams), new Action<tb_CTDatPhong_SanPham>(this.detach_tb_CTDatPhong_SanPhams));
			this._tb_NhomSanPham = default(EntityRef<tb_NhomSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money NOT NULL")]
		public decimal DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNSP", DbType="Int")]
		public System.Nullable<int> MaNSP
		{
			get
			{
				return this._MaNSP;
			}
			set
			{
				if ((this._MaNSP != value))
				{
					if (this._tb_NhomSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNSPChanging(value);
					this.SendPropertyChanging();
					this._MaNSP = value;
					this.SendPropertyChanged("MaNSP");
					this.OnMaNSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_SanPham_tb_CTDatPhong_SanPham", Storage="_tb_CTDatPhong_SanPhams", ThisKey="MaSanPham", OtherKey="MaSanPham")]
		public EntitySet<tb_CTDatPhong_SanPham> tb_CTDatPhong_SanPhams
		{
			get
			{
				return this._tb_CTDatPhong_SanPhams;
			}
			set
			{
				this._tb_CTDatPhong_SanPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NhomSanPham_tb_SanPham", Storage="_tb_NhomSanPham", ThisKey="MaNSP", OtherKey="MaNSP", IsForeignKey=true)]
		public tb_NhomSanPham tb_NhomSanPham
		{
			get
			{
				return this._tb_NhomSanPham.Entity;
			}
			set
			{
				tb_NhomSanPham previousValue = this._tb_NhomSanPham.Entity;
				if (((previousValue != value) 
							|| (this._tb_NhomSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_NhomSanPham.Entity = null;
						previousValue.tb_SanPhams.Remove(this);
					}
					this._tb_NhomSanPham.Entity = value;
					if ((value != null))
					{
						value.tb_SanPhams.Add(this);
						this._MaNSP = value.MaNSP;
					}
					else
					{
						this._MaNSP = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_NhomSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_CTDatPhong_SanPhams(tb_CTDatPhong_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.tb_SanPham = this;
		}
		
		private void detach_tb_CTDatPhong_SanPhams(tb_CTDatPhong_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.tb_SanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_TaiKhoan")]
	public partial class tb_TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private System.Nullable<bool> _IsAdmin;
		
		private EntitySet<tb_NhanVien> _tb_NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnIsAdminChanging(System.Nullable<bool> value);
    partial void OnIsAdminChanged();
    #endregion
		
		public tb_TaiKhoan()
		{
			this._tb_NhanViens = new EntitySet<tb_NhanVien>(new Action<tb_NhanVien>(this.attach_tb_NhanViens), new Action<tb_NhanVien>(this.detach_tb_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(1000)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Bit")]
		public System.Nullable<bool> IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this.OnIsAdminChanging(value);
					this.SendPropertyChanging();
					this._IsAdmin = value;
					this.SendPropertyChanged("IsAdmin");
					this.OnIsAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_TaiKhoan_tb_NhanVien", Storage="_tb_NhanViens", ThisKey="TenDangNhap", OtherKey="TenDangNhap")]
		public EntitySet<tb_NhanVien> tb_NhanViens
		{
			get
			{
				return this._tb_NhanViens;
			}
			set
			{
				this._tb_NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_NhanViens(tb_NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tb_TaiKhoan = this;
		}
		
		private void detach_tb_NhanViens(tb_NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tb_TaiKhoan = null;
		}
	}
}
#pragma warning restore 1591
